version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18  # Adjust based on your CDK project's requirements
    commands:
      - npm install -g aws-cdk
      - npm install
      - pip --version
  build:
    commands:
      - cdk synth
      - cdk deploy --require-approval never

