version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18  # Adjust based on your CDK project's requirements
    commands:
      - npm install -g aws-cdk
      - pip --version
      - pip install -r requirements.txt
  build:
    commands:
      - cdk synth
      - cdk deploy -c stage=dev --require-approval never

